services:

  db:
    image: postgres:18.3
    container_name: feedbackFlowDB
    mem_limit: 1536MB
    mem_reservation: 1024MB
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - "5434:5432"

  pgadmin:
    image: dpage/pgadmin4:9.13
    container_name: feedbackFlowPgadmin
    mem_reservation: 512MB
    mem_limit: 1024MB
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./pgadmin-data:/pgadmin
    ports:
      - "8082:80"
    networks:
      - backend
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}

  dotnet:
    container_name: aspNet
    build:
      context: .
      dockerfile: ./Dockerfile.HotReload
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://*:443;http://*:80
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ~/.aspnet/https:/https:ro
      - .:/app
    command: dotnet watch run --no-launch-profile


networks:
  backend:
    name: backend
    internal: false # in production, it should be true if you don't want to expose this network to the outside world
    driver: bridge
