# Build Code
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /app

COPY /feedbackFlowFront/feedbackFlowFront.csproj .
RUN dotnet restore "feedbackFlowFront.csproj"

COPY ./feedbackFlowFront .
RUN dotnet publish "feedbackFlowFront.csproj" --output /app/publish

# Runtime
FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine AS runtime
RUN addgroup -S dockergroup && adduser -S dockeruser -G dockergroup
USER dockeruser
WORKDIR /app
COPY --from=build /app/publish .
# RUN chown -R dockeruser:dockergroup /app
ENTRYPOINT [ "dotnet", "feedbackFlowFront.dll" ]