// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using feedbackFlowAPI.Helpers;

#nullable disable

namespace feedbackFlowAPI.Migrations
{
    [DbContext(typeof(FbfDbContext))]
    [Migration("20260307164508_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "class_level", new[] { "a", "b", "c", "d", "e", "f" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "question_type", new[] { "digital", "analog" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "student", "teacher", "admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "visibility", new[] { "private", "public" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassUser", b =>
                {
                    b.Property<int>("ClassesId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("ClassesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ClassUser");
                });

            modelBuilder.Entity("ContentTypeQuestion", b =>
                {
                    b.Property<int>("ContentTypesId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionsId")
                        .HasColumnType("integer");

                    b.HasKey("ContentTypesId", "QuestionsId");

                    b.HasIndex("QuestionsId");

                    b.ToTable("ContentTypeQuestion");
                });

            modelBuilder.Entity("ContentTypeQuestionAnswer", b =>
                {
                    b.Property<int>("ContentTypesId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionAnswersId")
                        .HasColumnType("integer");

                    b.HasKey("ContentTypesId", "QuestionAnswersId");

                    b.HasIndex("QuestionAnswersId");

                    b.ToTable("ContentTypeQuestionAnswer");
                });

            modelBuilder.Entity("ErrorTypeStudentResult", b =>
                {
                    b.Property<int>("ErrorTypesId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentResultsId")
                        .HasColumnType("integer");

                    b.HasKey("ErrorTypesId", "StudentResultsId");

                    b.HasIndex("StudentResultsId");

                    b.ToTable("ErrorTypeStudentResult");
                });

            modelBuilder.Entity("QuestionQuestionSet", b =>
                {
                    b.Property<int>("QuestionSetsId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionsId")
                        .HasColumnType("integer");

                    b.HasKey("QuestionSetsId", "QuestionsId");

                    b.HasIndex("QuestionsId");

                    b.ToTable("QuestionQuestionSet");
                });

            modelBuilder.Entity("QuestionSubject", b =>
                {
                    b.Property<int>("QuestionsId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectsId")
                        .HasColumnType("integer");

                    b.HasKey("QuestionsId", "SubjectsId");

                    b.HasIndex("SubjectsId");

                    b.ToTable("QuestionSubject");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Appendix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("appendix_pkey");

                    b.HasIndex("QuestionId");

                    b.ToTable("appendix", null, t =>
                        {
                            t.HasComment("(Billag)");
                        });
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassLevel")
                        .HasColumnType("class_level")
                        .HasColumnName("class_level");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<DateTime>("Year")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("classes_pkey");

                    b.HasIndex("CourseId");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.ContentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("contenttype_pkey");

                    b.ToTable("content_type", null, t =>
                        {
                            t.HasComment("(diagram, tekst)");
                        });
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name")
                        .HasComment("mat, fys, etc.");

                    b.HasKey("Id")
                        .HasName("courses_pkey");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.ErrorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("error_type");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("errortypes_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("error_types", (string)null);
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassLevel")
                        .HasColumnType("class_level")
                        .HasColumnName("class_level");

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Points")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("points");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int>("QuestionType")
                        .HasColumnType("question_type")
                        .HasColumnName("question_type");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("questions_pkey");

                    b.HasIndex("CourseId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.QuestionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int>("QuestionSetId")
                        .HasColumnType("integer")
                        .HasColumnName("question_set_id")
                        .HasComment("f.feks. svar til hele questionset i stedet for kun 1 question");

                    b.Property<string>("Url")
                        .HasColumnType("character varying")
                        .HasColumnName("url");

                    b.Property<int>("Visibility")
                        .HasColumnType("visibility")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("questionanswers_pkey");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionSetId");

                    b.ToTable("question_answers", (string)null);
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.QuestionCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Points")
                        .HasColumnType("character varying")
                        .HasColumnName("points");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int?>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id")
                        .HasName("questioncollections_pkey");

                    b.HasIndex("QuestionId");

                    b.ToTable("questioncollections", (string)null);
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.QuestionSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean")
                        .HasColumnName("is_draft")
                        .HasComment("if its assigned to students");

                    b.Property<bool>("IsExam")
                        .HasColumnType("boolean")
                        .HasColumnName("is_exam");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("questionsets_pkey");

                    b.ToTable("questionsets", (string)null);
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.StudentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createddate");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int>("QuestionSetId")
                        .HasColumnType("integer")
                        .HasColumnName("question_set_id");

                    b.Property<string>("StudentSelfAssessmentPoints")
                        .HasColumnType("character varying")
                        .HasColumnName("student_self_assessment_points");

                    b.Property<string>("TeacherFeedback")
                        .HasColumnType("character varying")
                        .HasColumnName("teacher_feedback");

                    b.Property<string>("TeacherPoint")
                        .HasColumnType("character varying")
                        .HasColumnName("teacher_point");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("studentresults_pkey");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionSetId");

                    b.HasIndex("UserId");

                    b.ToTable("StudentResults", (string)null);
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("subject")
                        .HasComment("trigonometri, vectors");

                    b.HasKey("Id")
                        .HasName("subjects_pkey");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("firstname");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("lastname");

                    b.Property<int>("UserRole")
                        .HasColumnType("user_role")
                        .HasColumnName("user_role");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ClassUser", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feedbackFlowAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentTypeQuestion", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.ContentType", null)
                        .WithMany()
                        .HasForeignKey("ContentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feedbackFlowAPI.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentTypeQuestionAnswer", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.ContentType", null)
                        .WithMany()
                        .HasForeignKey("ContentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feedbackFlowAPI.Entities.QuestionAnswer", null)
                        .WithMany()
                        .HasForeignKey("QuestionAnswersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErrorTypeStudentResult", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.ErrorType", null)
                        .WithMany()
                        .HasForeignKey("ErrorTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feedbackFlowAPI.Entities.StudentResult", null)
                        .WithMany()
                        .HasForeignKey("StudentResultsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuestionQuestionSet", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.QuestionSet", null)
                        .WithMany()
                        .HasForeignKey("QuestionSetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feedbackFlowAPI.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuestionSubject", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feedbackFlowAPI.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Appendix", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Question", "Question")
                        .WithMany("Appendices")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("fk_questions_to_appendix");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Class", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Course", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("fk_courses_to_classes");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.ErrorType", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.User", "User")
                        .WithMany("ErrorTypes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_users_to_errortypes");

                    b.Navigation("User");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Question", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Course", "Course")
                        .WithMany("Questions")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("fk_courses_to_questions");

                    b.HasOne("feedbackFlowAPI.Entities.Question", "QuestionNavigation")
                        .WithMany("InverseQuestionNavigation")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("fk_questions_to_questions");

                    b.HasOne("feedbackFlowAPI.Entities.User", "User")
                        .WithMany("Questions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_users_to_questions");

                    b.Navigation("Course");

                    b.Navigation("QuestionNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.QuestionAnswer", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Question", "Question")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("fk_questions_to_questionanswers");

                    b.HasOne("feedbackFlowAPI.Entities.QuestionSet", "QuestionSet")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("QuestionSetId")
                        .IsRequired()
                        .HasConstraintName("fk_questionsets_to_questionanswers");

                    b.Navigation("Question");

                    b.Navigation("QuestionSet");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.QuestionCollection", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Question", "Question")
                        .WithMany("QuestionCollections")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("fk_questions_to_questioncollections");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.StudentResult", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Question", "Question")
                        .WithMany("StudentResults")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("fk_questions_to_studentresults");

                    b.HasOne("feedbackFlowAPI.Entities.QuestionSet", "QuestionSet")
                        .WithMany("StudentResults")
                        .HasForeignKey("QuestionSetId")
                        .IsRequired()
                        .HasConstraintName("fk_questionsets_to_studentresults");

                    b.HasOne("feedbackFlowAPI.Entities.User", "User")
                        .WithMany("StudentResults")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_users_to_studentresults");

                    b.Navigation("Question");

                    b.Navigation("QuestionSet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Course", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Question", b =>
                {
                    b.Navigation("Appendices");

                    b.Navigation("InverseQuestionNavigation");

                    b.Navigation("QuestionAnswers");

                    b.Navigation("QuestionCollections");

                    b.Navigation("StudentResults");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.QuestionSet", b =>
                {
                    b.Navigation("QuestionAnswers");

                    b.Navigation("StudentResults");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.User", b =>
                {
                    b.Navigation("ErrorTypes");

                    b.Navigation("Questions");

                    b.Navigation("StudentResults");
                });
#pragma warning restore 612, 618
        }
    }
}
