// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using feedbackFlowAPI.Helpers;

#nullable disable

namespace feedbackFlowAPI.Migrations
{
    [DbContext(typeof(FbfDbContext))]
    [Migration("20260623193402_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "class_level", new[] { "a", "b", "c", "d" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "education", new[] { "hf", "hhx", "htx", "stx" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "exam_type", new[] { "digital", "analog" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "new_old_system", new[] { "new", "old" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "question_context", new[] { "yes_heavy", "yes_light", "no" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "question_difficulty", new[] { "hard", "medium", "easy" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "question_method_requirement", new[] { "apply_formula", "specific_method", "no_requirement" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "standard_question", new[] { "yes", "partially", "no", "with_a_twist" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "visibility", new[] { "private", "public" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassUser", b =>
                {
                    b.Property<int>("StudentClassesId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentsId")
                        .HasColumnType("integer");

                    b.HasKey("StudentClassesId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("ClassUser");
                });

            modelBuilder.Entity("ContentTypeQuestion", b =>
                {
                    b.Property<int>("ContentTypesId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionsId")
                        .HasColumnType("integer");

                    b.HasKey("ContentTypesId", "QuestionsId");

                    b.HasIndex("QuestionsId");

                    b.ToTable("ContentTypeQuestion");
                });

            modelBuilder.Entity("ContentTypeQuestionAnswer", b =>
                {
                    b.Property<int>("ContentTypesId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionAnswersId")
                        .HasColumnType("integer");

                    b.HasKey("ContentTypesId", "QuestionAnswersId");

                    b.HasIndex("QuestionAnswersId");

                    b.ToTable("ContentTypeQuestionAnswer");
                });

            modelBuilder.Entity("MistakeStudentResult", b =>
                {
                    b.Property<int>("MistakesId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentResultsId")
                        .HasColumnType("integer");

                    b.HasKey("MistakesId", "StudentResultsId");

                    b.HasIndex("StudentResultsId");

                    b.ToTable("MistakeStudentResult");
                });

            modelBuilder.Entity("QuestionSubject", b =>
                {
                    b.Property<int>("QuestionsId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectsId")
                        .HasColumnType("integer");

                    b.HasKey("QuestionsId", "SubjectsId");

                    b.HasIndex("SubjectsId");

                    b.ToTable("QuestionSubject");
                });

            modelBuilder.Entity("UserUserRole", b =>
                {
                    b.Property<int>("UserRolesId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("UserRolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserUserRole");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Appendix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("appendix_pkey");

                    b.HasIndex("QuestionId");

                    b.ToTable("appendix", null, t =>
                        {
                            t.HasComment("(Billag)");
                        });
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<ClassLevel>("ClassLevel")
                        .HasColumnType("class_level")
                        .HasColumnName("class_level");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Education>("Education")
                        .HasColumnType("education")
                        .HasColumnName("education");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Year")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("classes_pkey");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.ContentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("contenttype_pkey");

                    b.ToTable("content_types", null, t =>
                        {
                            t.HasComment("(diagram, tekst)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Text"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Algebraic"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Graph"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Figure"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Table"
                        });
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("courses_pkey");

                    b.ToTable("courses", null, t =>
                        {
                            t.HasComment("mat, fys, etc.");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Math"
                        });
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Mistake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("mistakes_pkey");

                    b.ToTable("mistakes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Presentation"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Documentation"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Argumentation"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Conclusion"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Calculation"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Insertion"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Inaccurate"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Technical"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Misunderstanding"
                        });
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<ClassLevel>("ClassLevel")
                        .HasColumnType("class_level")
                        .HasColumnName("class_level");

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Education>("Education")
                        .HasColumnType("education")
                        .HasColumnName("education");

                    b.Property<ExamType>("ExamType")
                        .HasColumnType("exam_type")
                        .HasColumnName("exam_type");

                    b.Property<string>("ImgSrc")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("img_src");

                    b.Property<NewOldSystem>("NewOldSystem")
                        .HasColumnType("new_old_system")
                        .HasColumnName("new_old_system");

                    b.Property<string>("Points")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("points");

                    b.Property<QuestionContext>("QuestionContext")
                        .HasColumnType("question_context")
                        .HasColumnName("question_context");

                    b.Property<QuestionDifficulty>("QuestionDifficulty")
                        .HasColumnType("question_difficulty")
                        .HasColumnName("question_difficulty");

                    b.Property<QuestionMethodRequirement>("QuestionMethodRequirement")
                        .HasColumnType("question_method_requirement")
                        .HasColumnName("question_method_requirement");

                    b.Property<StandardQuestion>("StandardQuestion")
                        .HasColumnType("standard_question")
                        .HasColumnName("standard_question");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("questions_pkey");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.QuestionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int>("QuestionSetId")
                        .HasColumnType("integer")
                        .HasColumnName("question_set_id")
                        .HasComment("f.feks. svar til hele questionset i stedet for kun 1 question");

                    b.Property<string>("Url")
                        .HasColumnType("character varying")
                        .HasColumnName("url");

                    b.Property<Visibility>("Visibility")
                        .HasColumnType("visibility")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("question_answers_pkey");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionSetId");

                    b.ToTable("question_answers", (string)null);
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.QuestionCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Points")
                        .HasColumnType("character varying")
                        .HasColumnName("points");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int?>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id")
                        .HasName("question_collections_pkey");

                    b.HasIndex("QuestionId");

                    b.ToTable("question_collections", (string)null);
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.QuestionQuestionSet", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int>("QuestionSetId")
                        .HasColumnType("integer")
                        .HasColumnName("question_set_id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("QuestionId", "QuestionSetId", "SubjectId");

                    b.HasIndex("QuestionSetId");

                    b.HasIndex("SubjectId");

                    b.ToTable("questions_question_sets", (string)null);
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.QuestionSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean")
                        .HasColumnName("is_draft")
                        .HasComment("if its assigned to students");

                    b.Property<bool>("IsExam")
                        .HasColumnType("boolean")
                        .HasColumnName("is_exam");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("question_sets_pkey");

                    b.HasIndex("TeacherId");

                    b.ToTable("question_sets", (string)null);
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.StudentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int>("QuestionSetId")
                        .HasColumnType("integer")
                        .HasColumnName("question_set_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<int?>("StudentSelfAssessmentPoints")
                        .HasColumnType("integer")
                        .HasColumnName("student_self_assessment_points");

                    b.Property<string>("TeacherFeedback")
                        .HasColumnType("character varying")
                        .HasColumnName("teacher_feedback");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<int?>("TeacherPoint")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_point");

                    b.HasKey("Id")
                        .HasName("student_results_pkey");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionSetId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("student_results", (string)null);
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("subjects_pkey");

                    b.ToTable("subjects", null, t =>
                        {
                            t.HasComment("trigonometri, vectors");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Combinatorics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Differential Calculus"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Quadratic polynomial"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Regression"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Exponential function"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Binomial distribution"
                        });
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("first_name");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("userroles_pkey");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Teacher"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("ClassUser", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Class", null)
                        .WithMany()
                        .HasForeignKey("StudentClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feedbackFlowAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentTypeQuestion", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.ContentType", null)
                        .WithMany()
                        .HasForeignKey("ContentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feedbackFlowAPI.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentTypeQuestionAnswer", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.ContentType", null)
                        .WithMany()
                        .HasForeignKey("ContentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feedbackFlowAPI.Entities.QuestionAnswer", null)
                        .WithMany()
                        .HasForeignKey("QuestionAnswersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MistakeStudentResult", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Mistake", null)
                        .WithMany()
                        .HasForeignKey("MistakesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feedbackFlowAPI.Entities.StudentResult", null)
                        .WithMany()
                        .HasForeignKey("StudentResultsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuestionSubject", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feedbackFlowAPI.Entities.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUserRole", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.UserRole", null)
                        .WithMany()
                        .HasForeignKey("UserRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feedbackFlowAPI.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Appendix", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Question", "Question")
                        .WithMany("Appendices")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("fk_questions_to_appendix");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Class", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Course", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_courses_to_classes");

                    b.HasOne("feedbackFlowAPI.Entities.User", "Teacher")
                        .WithMany("TeacherClasses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_to_classes");

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Question", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Course", "Course")
                        .WithMany("Questions")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("fk_courses_to_questions");

                    b.HasOne("feedbackFlowAPI.Entities.User", "User")
                        .WithMany("Questions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_users_to_questions");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.QuestionAnswer", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Question", "Question")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("fk_questions_to_questionanswers");

                    b.HasOne("feedbackFlowAPI.Entities.QuestionSet", "QuestionSet")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("QuestionSetId")
                        .IsRequired()
                        .HasConstraintName("fk_questionsets_to_questionanswers");

                    b.Navigation("Question");

                    b.Navigation("QuestionSet");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.QuestionCollection", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Question", "Question")
                        .WithMany("QuestionCollections")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("fk_questions_to_questioncollections");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.QuestionQuestionSet", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Question", "Question")
                        .WithMany("QuestionSets")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_to_questionquestionset");

                    b.HasOne("feedbackFlowAPI.Entities.QuestionSet", "QuestionSet")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questionsets_to_questionquestionset");

                    b.HasOne("feedbackFlowAPI.Entities.Subject", "Subject")
                        .WithMany("QuestionQuestionSets")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subject_to_questionquestionset");

                    b.Navigation("Question");

                    b.Navigation("QuestionSet");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.QuestionSet", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.User", "Teacher")
                        .WithMany("QuestionSets")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_to_questionset");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.StudentResult", b =>
                {
                    b.HasOne("feedbackFlowAPI.Entities.Question", "Question")
                        .WithMany("StudentResults")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("fk_questions_to_studentresults");

                    b.HasOne("feedbackFlowAPI.Entities.QuestionSet", "QuestionSet")
                        .WithMany("StudentResults")
                        .HasForeignKey("QuestionSetId")
                        .IsRequired()
                        .HasConstraintName("fk_questionsets_to_studentresults");

                    b.HasOne("feedbackFlowAPI.Entities.User", "Student")
                        .WithMany("StudentResults")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("fk_student_to_studentresults");

                    b.HasOne("feedbackFlowAPI.Entities.User", "Teacher")
                        .WithMany("TeacherStudentResults")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("fk_teacher_to_studentresults");

                    b.Navigation("Question");

                    b.Navigation("QuestionSet");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Course", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Question", b =>
                {
                    b.Navigation("Appendices");

                    b.Navigation("QuestionAnswers");

                    b.Navigation("QuestionCollections");

                    b.Navigation("QuestionSets");

                    b.Navigation("StudentResults");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.QuestionSet", b =>
                {
                    b.Navigation("QuestionAnswers");

                    b.Navigation("Questions");

                    b.Navigation("StudentResults");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.Subject", b =>
                {
                    b.Navigation("QuestionQuestionSets");
                });

            modelBuilder.Entity("feedbackFlowAPI.Entities.User", b =>
                {
                    b.Navigation("QuestionSets");

                    b.Navigation("Questions");

                    b.Navigation("StudentResults");

                    b.Navigation("TeacherClasses");

                    b.Navigation("TeacherStudentResults");
                });
#pragma warning restore 612, 618
        }
    }
}
